### ISSUE TITLE
"mSocket.close" in mainThread

### ISSUE THREAD

**Issue by duzhenfeng** [crossbario/autobahn-java#153] opened 2017-06-03 13:57 UTC
[WebSocketConnection.java](https://github.com/crossbario/autobahn-java/blob/master/autobahn/src/main/java/io/crossbar/autobahn/WebSocketConnection.java)
In the line 213, the socket close in mainThread

**Comment by om26er** [comment] 2017-06-03 15:25
You are right, but from my understanding Socket.close() is not a network operation, It only closes the socket locally without notifying the remote end.

The reason we ensure to close the socket before calling onClose is that a race condition could happen if Socket.close() is called in a separate thread, so if the app code tries to connect the websocket again on the onClose callback, we would hit this [codepath](https://github.com/crossbario/autobahn-java/blob/master/autobahn/src/main/java/io/crossbar/autobahn/WebSocketConnection.java#L245).

Is there a case where you found this to be a problem or is that something you sighted during code inspection ?

**Comment by duzhenfeng** [comment] 2017-06-04 05:54
I received this error from server.
`io.crossbar.autobahn.WebSocketConnection: fail connection [code = 6, reason = Server error 403 (Forbidden)`
My application is crashed with throwing this error:
`io.crossbar.autobahn.demogallery E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                  Process: io.crossbar.autobahn.demogallery, PID: 13885
                                                                                  android.os.NetworkOnMainThreadException
                                                                                      at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1145)
                                                                                      at com.android.org.conscrypt.OpenSSLSocketImpl.close(OpenSSLSocketImpl.java:1009)
                                                                                      at io.crossbar.autobahn.WebSocketConnection.failConnection(WebSocketConnection.java:212)
                                                                                      at io.crossbar.autobahn.WebSocketConnection.access$1600(WebSocketConnection.java:46)
                                                                                      at io.crossbar.autobahn.WebSocketConnection$2.handleMessage(WebSocketConnection.java:536)
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                      at android.os.Looper.loop(Looper.java:136)
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:5113)
                                                                                      at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                      at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:796)
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:612)
                                                                                      at dalvik.system.NativeStart.main(Native Method)`

**Comment by om26er** [comment] 2017-06-05 09:17
Will look into this, in my personal experiments Socket.close() did not throw NetworkOnMainThreadException so need to dive deep into it.

One thing we could do is to try and close the Socket in a new thread and find a way to call the onClose from the main thread afterwards.

**Comment by oberstet** [comment] 2017-06-06 17:03
marking this a potential bug, but this needs investigation. thing is, as far as I know and if that still applies, on Android, no network activity must happen on the main/UI thread. none at all.

question is, what is "network activity"?

definitely initial DNS lookup, and of course subsequent network communication.

_closing_ a socket might count as "network activity" - dunno.

**Comment by mifkamaz** [comment] 2017-07-08 04:50
Same problem

**Comment by cedricshih** [comment] 2017-08-03 03:15
I also encountered this issue.

```
  android.os.NetworkOnMainThreadException
      at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1303)
      at com.android.org.conscrypt.Platform.blockGuardOnNetwork(Platform.java:300)
      at com.android.org.conscrypt.OpenSSLSocketImpl.shutdownAndFreeSslNative(OpenSSLSocketImpl.java:1194)
      at com.android.org.conscrypt.OpenSSLSocketImpl.close(OpenSSLSocketImpl.java:1189)
      at io.crossbar.autobahn.websocket.WebSocketConnection.closeAndCleanup(WebSocketConnection.java:394)
      at io.crossbar.autobahn.websocket.WebSocketConnection.access$1300(WebSocketConnection.java:34)
      at io.crossbar.autobahn.websocket.WebSocketConnection$2.handleMessage(WebSocketConnection.java:485)
      at android.os.Handler.dispatchMessage(Handler.java:102)
      at android.os.Looper.loop(Looper.java:154)
      at android.app.ActivityThread.main(ActivityThread.java:6119)
      at java.lang.reflect.Method.invoke(Native Method)
      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

```

And I guess, FIN packet may be sent upon closing socket. Hence Socket.close() was classified as network operation in Android.

BTW, I tried to add one line of code at line 671 of WebSocketReader.java to delegate socket closing to reader thread:

```
mSocket.close();
```

And this exception was never thrown. But I'm not sure it is a good solution or not.

**Comment by oberstet** [comment] 2017-08-03 21:21
> BTW, I tried to add one line of code at line 671 of WebSocketReader.java to delegate socket closing to reader thread:

Yes, closing the socket on the reader thread is a good idea! I think we should do that change. @cedricshih Q: you did leave the code for closing the socket on the main thread in, and _added_ that line?


@om26er likely similar for both the reading and writing socket legs. Closing of sockets should be done on the respective background thread.

**Comment by cedricshih** [comment] 2017-08-04 02:03
@oberstet Yes, I leave the code run by main thread as is. Just added that line of code for reader thread. I guess **isConnected()** returns false so main thread won't invoke **mSocket.close()**.
```
public class WebSocketConnection implements WebSocket {
    ...
    private void closeAndCleanup() {
        ...
        if (isConnected()) {
            try {
                mSocket.close();
            } catch (IOException e) {
                if (DEBUG) e.printStackTrace();
            }
        }
```

**Comment by cedricshih** [comment] 2017-08-04 07:33
Today I got this exception from **failConnection()**:
```
 Exception in thread "main" android.os.NetworkOnMainThreadException
     at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1303)
     at com.android.org.conscrypt.Platform.blockGuardOnNetwork(Platform.java:300)
     at com.android.org.conscrypt.OpenSSLSocketImpl.shutdownAndFreeSslNative(OpenSSLSocketImpl.java:1194)
     at com.android.org.conscrypt.OpenSSLSocketImpl.close(OpenSSLSocketImpl.java:1189)
     at io.crossbar.autobahn.websocket.WebSocketConnection.failConnection(WebSocketConnection.java:200)
     at io.crossbar.autobahn.websocket.WebSocketConnection.access$1600(WebSocketConnection.java:34)
     at io.crossbar.autobahn.websocket.WebSocketConnection$2.handleMessage(WebSocketConnection.java:519)
     at android.os.Handler.dispatchMessage(Handler.java:102)
     at android.os.Looper.loop(Looper.java:241)
     at android.app.ActivityThread.main(ActivityThread.java:6274)
     at java.lang.reflect.Method.invoke(Native Method)
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by rmanaugmedix** [comment] 2017-08-11 11:08
I am also getting the similar exception:
```
android.os.NetworkOnMainThreadException
      at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1303)
      at com.android.org.conscrypt.Platform.blockGuardOnNetwork(Platform.java:300)
      at com.android.org.conscrypt.OpenSSLSocketImpl.shutdownAndFreeSslNative(OpenSSLSocketImpl.java:1194)
      at com.android.org.conscrypt.OpenSSLSocketImpl.close(OpenSSLSocketImpl.java:1189)
      at io.crossbar.autobahn.websocket.WebSocketConnection.closeAndCleanup(WebSocketConnection.java:394)
      at io.crossbar.autobahn.websocket.WebSocketConnection.access$1300(WebSocketConnection.java:34)
      at io.crossbar.autobahn.websocket.WebSocketConnection$2.handleMessage(WebSocketConnection.java:485)
      at android.os.Handler.dispatchMessage(Handler.java:102)
      at android.os.Looper.loop(Looper.java:154)
      at android.app.ActivityThread.main(ActivityThread.java:6119)
      at java.lang.reflect.Method.invoke(Native Method)
      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

As per @cedricshih's suggestion, after adding `mSocket.close();` in WebSocketReader.java the issue is resolved.
As @oberstet  mentioned we have to add this on both WebSocketReader.java and WebSocketWriter.java, my question is where I should put the `mSocket.close();` on **WebSocketWriter.java** ?

**Comment by rmanaugmedix** [comment] 2017-08-11 12:49
Another exception found:
```
E/AndroidRuntime( 7147): android.os.NetworkOnMainThreadException
E/AndroidRuntime( 7147):        at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1145)
E/AndroidRuntime( 7147):        at com.android.org.conscrypt.OpenSSLSocketImpl.close(OpenSSLSocketImpl.java:1009)
E/AndroidRuntime( 7147):        at io.crossbar.autobahn.websocket.WebSocketConnection.failConnection(WebSocketConnection.java:205)
E/AndroidRuntime( 7147):        at io.crossbar.autobahn.websocket.WebSocketConnection.access$1600(WebSocketConnection.java:35)
E/AndroidRuntime( 7147):        at io.crossbar.autobahn.websocket.WebSocketConnection$2.handleMessage(WebSocketConnection.java:524)
E/AndroidRuntime( 7147):        at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 7147):        at android.os.Looper.loop(Looper.java:149)
E/AndroidRuntime( 7147):        at android.app.ActivityThread.main(ActivityThread.java:5045)
E/AndroidRuntime( 7147):        at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 7147):        at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime( 7147):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
E/AndroidRuntime( 7147):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602)
E/AndroidRuntime( 7147):        at dalvik.system.NativeStart.main(Native Method)
W/System.err( 7147): javax.net.ssl.SSLException: Read error: ssl=0xfa33ab90: I/O error during system call, Connection timed out
W/ActivityManager(  534):   Force finishing activity com.augmedix.glass.doc.primary/com.augmedix.glass.doc.AugmedixSecureLayerActivity
W/System.err( 7147):    at com.android.org.conscrypt.NativeCrypto.SSL_read(Native Method)
W/System.err( 7147):    at com.android.org.conscrypt.OpenSSLSocketImpl$SSLInputStream.read(OpenSSLSocketImpl.java:689)
W/System.err( 7147):    at org.apache.http.impl.io.AbstractSessionInputBuffer.fillBuffer(AbstractSessionInputBuffer.java:103)
W/System.err( 7147):    at org.apache.http.impl.io.AbstractSessionInputBuffer.readLine(AbstractSessionInputBuffer.java:191)
W/System.err( 7147):    at org.apache.http.impl.conn.DefaultResponseParser.parseHead(DefaultResponseParser.java:82)
W/System.err( 7147):    at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:174)
W/System.err( 7147):    at org.apache.http.impl.AbstractHttpClientConnection.receiveResponseHeader(AbstractHttpClientConnection.java:180)
W/System.err( 7147):    at org.apache.http.impl.conn.DefaultClientConnection.receiveResponseHeader(DefaultClientConnection.java:235)

```

**Comment by om26er** [comment] 2017-08-12 20:09
I am looking into this, will get back when I have something.

**Comment by luoyushouchai** [comment] 2017-09-01 08:53
Connect web socket and close wifi will throw the exception:
`
 android.os.NetworkOnMainThreadException
                                                                      at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1288)
                                                                      at com.android.org.conscrypt.OpenSSLSocketImpl.shutdownAndFreeSslNative(OpenSSLSocketImpl.java:1146)
                                                                      at com.android.org.conscrypt.OpenSSLSocketImpl.close(OpenSSLSocketImpl.java:1141)
                                                                      at com.yiqixie.meet.websocket.WebSocketConnection.failConnection(WebSocketConnection.java:204)
                                                                      at com.yiqixie.meet.websocket.WebSocketConnection.access$1600(WebSocketConnection.java:34)
                                                                      at com.yiqixie.meet.websocket.WebSocketConnection$2.handleMessage(WebSocketConnection.java:523)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                      at android.os.Looper.loop(Looper.java:207)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5710)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:900)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:761)
`

**Comment by om26er** [comment] 2017-09-01 10:34
Thanks, I was able to reproduce the issue. The reason I was not able to reproduce this issue is because I was using websocket and this issue only happened with TLS based connection.

**Comment by om26er** [comment] 2017-09-01 11:07
This https://github.com/crossbario/autobahn-java/pull/271 fixes the issue.

**Comment by om26er** [comment] 2017-09-02 21:17
#271 landed.

**Closed by om26er** 2017-09-02 21:17 UTC
Labels: bug, needs-investigation
