### ISSUE TITLE
getOrDefault in WebSocketConnection.java always returns the default value

### ISSUE THREAD

**Issue by yashovardhan99** [crossbario/autobahn-java#432] opened 2019-03-09 20:11 UTC
In [line 646](https://github.com/crossbario/autobahn-java/blob/master/autobahn/src/main/java/io/crossbar/autobahn/websocket/WebSocketConnection.java#L645) of the file [WebSocketConnection.java, ](https://github.com/crossbario/autobahn-java/blob/master/autobahn/src/main/java/io/crossbar/autobahn/websocket/WebSocketConnection.java)

    String protocol = getOrDefault(serverHandshake.headers,
                                    "Sec-WebSocket-Protocol", null);`

the function `getOrDefault` is called. [This function](https://github.com/crossbario/autobahn-java/blob/e8c2028c0790b34e2d37104382708ecc953f064c/autobahn/src/main/java/io/crossbar/autobahn/websocket/WebSocketConnection.java#L515) then checks `if (obj.containsKey(key)` and returns the value if the key is present or the default value otherwise.

We had the key `Sec-WebSocket-Protocol` in our map (I printed the map within this function as well) and it was set to the value `wamp.2.cbor`. However, the if condition never gets executed and the default value (null) is always returned.

I am not sure what might be causing this issue. I fixed it temporarily by making the function return `wamp.2.cbor` instead of the default value for the time being (but that won't work for everyone obviously).

This is also the root cause of the issue #420 (and probably even #146 ). Atleast, I can tell that from my experience of forking this library and figuring out this issue (which took multiple hours), this is the root issue!

I don't know what sorcery this is or how this could be fixed but yes, this is a completely real issue and this was the root cause of our development being stuck for more than a week. And this, THIS was the main issue. Changing this one line of code fixed the entire thing!

**Comment by om26er** [comment] 2019-03-09 20:17
@yashovardhan99 I can look into the issue, can you tell if the issue you are seeing only happens when using Nexus router or do you see that issue with Crossbar as well ?

A blind guess: It could be that `Sec-WebSocket-Protocol` is in lower cases in your router ?

**Comment by yashovardhan99** [comment] 2019-03-09 20:24
@om26er we're using crossbar. And I checked the case, it's the exact match. I know this sounds strange but yeah, this happened.

**Comment by om26er** [comment] 2019-03-09 20:31
Could please some sample code that I could use to reproduce that issue ? More information about your setup would be useful as well i.e. version number of autobahn-java, crossbar, your OS etc.

**Comment by yashovardhan99** [comment] 2019-03-09 20:40
@om26er I'll share some sample code and logs with you tomorrow (it's past 2 am here:)

This issue seems to happen in both the latest and the 2nd latest version of the library. I had downloaded the zip of your latest release v19.3.1 to debug this issue. The mobile OS - Android Pie (Absurd 9.0 and also on Android N)

**Comment by om26er** [comment] 2019-04-16 20:38
@yashovardhan99 Hello! Is there an update on that, do you think we can close this issue ?

**Closed** 2019-04-22 09:54 UTC

**Comment by azamat-sharapov** [comment] 2020-07-15 11:48
I was having similar problem today. In my case, I'm using [Caddy](https://caddyserver.com/) as a server, which proxies requests to [nexus router](https://github.com/gammazero/nexus). Problem was that Caddy returns HTTP headers in different case, instead of `Sec-WebSocket-Protocol`, it returns `Sec-Websocket-Protocol` (notice lowecase S). I came to conclusion, that it's autobahn-java problem, because [it relies](https://github.com/crossbario/autobahn-java/blob/c48c8d125f7eaa4778683e72cd49af14e6a8ba06/autobahn/src/main/java/io/crossbar/autobahn/websocket/WebSocketConnection.java#L634)  on header key case, when it [should not](https://caddy.community/t/different-capitalization-on-response-headers/5699/2).

As a workaround, I've added these lines in [ServerHandshake.java](https://github.com/crossbario/autobahn-java/blob/c48c8d125f7eaa4778683e72cd49af14e6a8ba06/autobahn/src/main/java/io/crossbar/autobahn/websocket/messages/ServerHandshake.java#L12):

```java
        for (Map.Entry<String, String> entry : headers.entrySet()) {
            this.headers.put(entry.getKey().toLowerCase(), entry.getValue());
        }
```

and changed all hardcoded header strings in other files into lowercase.

**Comment by oberstet** [comment] 2020-07-15 12:38
>  because it relies on header key case ..

yes, this is wrong: HTTP header keys are case insensitive

> As a workaround, 

yeah, I can see how this works, and actually I think this is a good place to add normalization to lowercase for those headers! straight forward. @om26er I think we should add a fix similar to this. what do you think?
